### ISSUE TITLE
Minimal Hand: demo.py , CUBLAS_STATUS_ALLOC_FAILED

### ISSUE THREAD

**Issue by malwaru** [oarriaga/paz#208]
Could not run the script minimal_hand/examples/demo.py because of the error "CUBLAS_STATUS_ALLOC_FAILED"

**Comment by malwaru** [comment]
FIxed the issue by adding the following lines of code

```
import tensorflow as tf
gpus = tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(gpus[0], True)
```

**Comment by malwaru** [comment]
Fixed the issue by adding the following lines of code add the top of the file

```
import tensorflow as tf
gpus = tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(gpus[0], True)
```
